site_name: Drift Protocol
docs_dir: .
nav:
  - Home:
      - README: README.md
      - For C++: cpp/README.md
      - For Python: python/README.md
  - API Reference:
      - docs/api/common.md
      - docs/api/meta.md
      - docs/api/triggering.md

repo_name: panda-official/DriftProtocol
repo_url: https://github.com/panda-official/DriftProtocol
edit_uri: edit/develop/docs

extra:
  homepage: https://panda.technology
# Configuration
theme:
  name: material
  logo: docs/img/logo.svg
  favicon: docs/img/favicon.png
  language: en
  palette:
    primary: black
  font:
    text: Roboto
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - plantuml_markdown:
      format: svg

plugins:
  - same-dir
