name: "download-protoc"
description: "Download protoc"
runs:
  using: "composite"
  steps:
    - name: "Parse version and download protoc"
      shell: bash
      working-directory: ./python
      run: |
        sudo apt-get update && sudo apt-get install -y wget unzip && sudo apt-get remove -y python3-protobuf
        export PROTO_VERSION=`cat setup.py | grep "PROTOBUF_VERSION = "| grep -Po "((\d+\.)+\d+)"`

        wget -O protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v${PROTO_VERSION}/protoc-${PROTO_VERSION}-linux-x86_64.zip
        unzip protoc.zip
        chmod +x ${PWD}/bin/
        sudo mv ${PWD}/bin/protoc /usr/local/bin 
        protoc --version
